### ISSUE TITLE
eBlocker Mobile: 2.6.2 is not compatible with Passepartout app

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#107]
In eOS 2.6.2 the compression was disabled in eBlocker Mobile.

A [soft migration](https://community.openvpn.net/openvpn/wiki/VORACLE) was chosen to support client configurations created with eOS 2.5 or earlier, so the server pushes the following option to the client to disable the compression:

    push "compress stub-v2"

The [Passepartout app](https://github.com/passepartoutvpn) does not seem to use `openvpn` but the `tunnelkit` library, which is confused by the option `compress stub-v2`.

The error message is:

    Server has non-LZO compression enabled and this is currently unsupported (framing=compress)

**Comment by keeshux** [comment]
The `stub-v2` argument [is now supported](https://github.com/passepartoutvpn/tunnelkit/commit/4dc3eee).

**Comment by eblosug** [comment]
Great, thanks. I tested eBlocker Mobile with Passepartout 1.16.0 successfully.
