### ISSUE TITLE
eBlocker hangs up 

### ISSUE THREAD

**Issue by PIOTA89** [eblocker/eblocker#112]
Hello, i experienced the issue that my EBlocker on a raspberry pi 4 with enabled HTTPS Feature and installed certificate on my devices hangs up after some hours. 

Then i need to restart the eblocker and it works again. I can reach the frontend and the backend without any problems. 

Enclosed is the diagnostic report. Hope that helps. 

[eblocker diagnostic report.zip](https://github.com/eblocker/eblocker/files/6489387/eblocker.diagnostic.report.zip)

**Comment by eblosug** [comment]
How did you restart the eBlocker after the hang-up?

* Via the settings
* or did you pull the power plug?

Did you get any error messages in the browser?

**Comment by PIOTA89** [comment]
Hi, 

I restarted the eBlocker via the settings and got no error messages. For now, everything works fine. 

-- 
Mit freundlichen Grüßen
—
Paul Schumacher

Hochgarten 9
A-3325 Ferschnitz

Mobil.: 0664 5515017
E-Mail: ***@***.***

**Comment by eblosug** [comment]
OK, thank you. I am closing this issue for now because there is currently not enough information to debug it.
