### ISSUE TITLE
eblocker icapserver build failure

### ISSUE THREAD

**Issue by h07d0q** [eblocker/eblocker#172]
Hello,

I'm trying to install eblocker in a proxmox LXC.
At the point of building and testing front- and backend I get following result while compiling the icapserver:
`Results :

Failed tests:
  MacPrefixTest.existing:40 expected:<[???????????HangZhou Delan Technology Co.,Ltd?]> but was:<[?????????????????????????????????HangZhou Delan Technology Co.,Ltd???]>

Tests run: 1813, Failures: 1, Errors: 0, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:26 min
[INFO] Finished at: 2021-10-13T21:12:06Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.13:test (default-test) on project eblocker-icapserver: There are test failures.
[ERROR]
[ERROR] Please refer to /home/user/src/eblocker/eblocker-icapserver/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

Has someone an advice, what could solve the problem?

**Comment by eblosug** [comment]
This looks like an encoding issue. The file `eblocker-icapserver/src/main/resources/mac-prefixes.txt` is UTF-8 encoded but it is read with the default encoding of the platform. The problem could be that the test works only with a default encoding of UTF-8. Does it work when you set the environment variable `LANG=en_US.UTF-8`?

**Comment by h07d0q** [comment]
Sadly the variable is already set like you suggested. (Could have been so easy)

I did not find the MAC prefix of the containers eth0 7E:40:99 in the list - can this be the problem?

**Comment by eblosug** [comment]
The MAC address of your build machine (or container) should not matter to the unit tests.

Maybe Maven uses another encoding for compiling the Java source files.

You could try to let Maven use UTF-8 explicitly:

    mvn -Dproject.build.sourceEncoding=UTF-8 ...

**Comment by h07d0q** [comment]
This does not help, too... Still the same error.
I tried to delete the line with "HangZhou Dela..." but this throws an error, too.

I get some warnings at the start of the test:

```
root@eblocker ~/eblocker/eblocker-icapserver# mvn -Dproject.build.sourceEncoding=UTF-8 test

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
But I don't think this correlates

I will try now to just run mvn compile...
Notes:
apt install bzip2
root@eblocker ~/eblocker/eblocker-ui# ./node ../node_modules/jpegtran-bin/lib/install.js
root@eblocker ~/eblocker/eblocker-ui# ./node ../node_modules/optipng-bin/lib/install.js
export OPENSSL_CONF=/etc/ssl
root@eblocker ~/eblocker/eblocker-ui# mvn clean
root@eblocker ~/eblocker/eblocker-ui# mvn compile
Success!

But starting with mvn exec:exec I get two following Errors:
```
2021-10-16 13:04:50,698 [ERROR]                   org.eblocker.server.app.EblockerServerApp [main] - Initializing subsystem HTTP_SERVER$java.util.concurrent.ExecutionException:
com.google.inject.ProvisionException: Unable to provision, see the following errors:
1) [Guice/ErrorInjectingConstructor]:
EblockerException: Could not find serial in CPU info                                                
at DeviceRegistrationProperties.<init>(DeviceRegistrationProperties.java:144)                                                           
at EblockerModule.configure(EblockerModule.java:263)                                                                                    
at SslService.<init>(SslService.java:103)                                                                                                   
\_ for 9th parameter                                                                                                                
at EblockerModule.configure(EblockerModule.java:275)                                                                                    
at SSLContextHandler.<init>(SSLContextHandler.java:93)                                                                                      
\_ for 8th parameter                                                                                                                
at EblockerModule.configure(EblockerModule.java:276)                                                                                    
at EblockerHttpsServer.<init>(EblockerHttpsServer.java:254)                                                                                 
\_ for 11th parameter
 
at EblockerModule.configure(EblockerModule.java:277)                                                                                   
while locating EblockerHttpsServer                                                                                                    
Learn more:     
https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
```

cpuid shows the host amd64 without serial. Someone having an idea how I can pass the ID, or how eBlocker might run without serial?

**Comment by eblosug** [comment]
Does [this fix](https://github.com/eblocker/eblocker/commit/83e0f7979f36fe57e50fc031cdcf60308cf84f1d) solve the UTF-8 encoding problem?

You can work around the CPU serial issue by writing a file `cpuinfo.txt` somewhere with a serial number of the form

    Serial: 0123456789abcdef

Then write a configuration file `/opt/eblocker-icap/conf/configuration.properties` with the content:

    system.path.cpu.info=/some/path/to/cpuinfo.txt

**Comment by h07d0q** [comment]
I don't remember clearly but I think it didn't solve the problem.
Since I read in the last newsletter that there will be a version for VMs I will be waiting and close this issue
