### ISSUE TITLE
eblocker spams the network with ARP requests

### ISSUE THREAD

**Issue by LMH01** [eblocker/eblocker#249]
I noticed in wireshark that the eblocker spams my network with ARP requests.
Is this intentional or a bug?

My eblocker os is 2.9.1

**Comment by eblosug** [comment]
This is intentional. It scans for new devices in the network.

You can change the frequency in the settings at Devices / Device Discovery / Automatic device discovery.

**Comment by LMH01** [comment]
Thanks for your response I will take a look at the settings, you can close the issue.
