### ISSUE TITLE
Server certificate must have a validity period of 825 days or fewer.

### ISSUE THREAD

**Issue by eblocker** [eblocker/eblocker#4]
There is a new [requirement](https://support.apple.com/en-us/HT210176) for TLS server certificates in iOS 13 and macOS 10.15:

> TLS server certificates must have a validity period of 825 days or fewer (as expressed in the NotBefore and NotAfter fields of the certificate).

Currently, eBlocker's server certificate has a validity of 3 years (1095 days) if the root certificate has the same validity period.

Workaround: create new root certificate with 2 years.

**Comment by eblocker** [comment]
Now it's only 398 days:
https://www.digicert.com/position-on-1-year-certificates/

I updated the title accordingly.

**Comment by mainzelM** [comment]
Hm, doesn't that mean that we just have to change the default value of ca.cert.max.validity.months from 36 to 12?

**Comment by eblosug** [comment]
> Now it's only 398 days:
> https://www.digicert.com/position-on-1-year-certificates/
> 
> I updated the title accordingly.

But [Apple's support document](https://support.apple.com/en-us/HT211025) says:

> This change will not affect certificates issued from user-added or administrator-added Root CAs

So the 398 day rule does not apply to server certificates issued by eBlocker's CA. I changed the title back to 825 days.

**Comment by eblosug** [comment]
> Hm, doesn't that mean that we just have to change the default value of ca.cert.max.validity.months from 36 to 12?

eBlocker's CA certificate can still be valid for 36 months. Only the server certificates issued by the CA must have a validity period of 825 days or fewer.

Reducing the CA's validity to 12 or 24 months is only a work-around (because the CA does not issue server certificates that exceed its own validity period).

**Comment by eblosug** [comment]
Fixed in 2.5.1
