### ISSUE TITLE
Disabled domain blockers are re-enabled after reboot

### ISSUE THREAD

**Issue by eblosug** [eblocker/eblocker#71]
How to reproduce:

* Go to Settings / Blocker / Overview
* Disable one of the domain blockers: Ad, Tracker, Malware
* Restart the Icapserver or reboot
* Now all domain blockers are enabled again.

**Comment by eblosug** [comment]
The problem is that the `ParentalControlFilterListsService` overwrites all meta data of builtin filters at startup:

    ParentalControlFilterListsService constructor -> update() -> replaceBuiltinMetaData()

The disabled flag in the database entity `ParentalControlFilterMetaData:n` is therfore overwritten.

**Comment by mainzelM** [comment]
Hm, what I don't understand: why are lists not related to parent-control present in the file read by `ParentalControlFilterListsService` (i.e. present in parentalcontrol-filter.json)?

**Comment by eblosug** [comment]
I am not sure what you mean by "not related", for example the Tracker domain filter is ID 9 in `parentalcontrol-filter.json`.

**Comment by mainzelM** [comment]
I mean that Tracker domain filtering is not related to parental control. Its a different category of filtering and also not shown in the list of parental control filters. So why is it listed in the JSON file for parental control at all?

**Comment by mainzelM** [comment]
I took a deeper dive into the code and as it seams, the "parental control" filters also include all standard eBlocker filters.

I wrote a small fix for this issue and will push a PR tonight or tomorrow.

**Comment by eblosug** [comment]
> I mean that Tracker domain filtering is not related to parental control. Its a different category of filtering and also not shown in the list of parental control filters. So why is it listed in the JSON file for parental control at all?

The naming is confusing. The reason is probably that the service was first used only for parental controls and later for other purposes. I have added an issue for doing a refactoring: #72.
